# Generated by Django 5.1.15 on 2026-09-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
